# Generated by Django 3.0.5 on 2021-04-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_choice', models.TextField()),
                ('enter_password', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('group', models.TextField()),
                ('calories', models.TextField()),
                ('fat', models.TextField()),
                ('protein', models.TextField()),
                ('carbs', models.TextField()),
                ('allergies', models.TextField()),
                ('price', models.FloatField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('state', models.TextField()),
                ('placed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceCalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField()),
                ('price', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('tax', models.FloatField()),
                ('revenue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='')),
                ('table_number', models.IntegerField(default=-1)),
                ('refill_request', models.BooleanField(default=False)),
                ('drink_selections', models.TextField(blank=True)),
                ('call_waitstaff', models.BooleanField(default=False)),
                ('call_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('placed_at', models.DateTimeField()),
                ('state', models.TextField()),
                ('quantity', models.IntegerField()),
                ('allergy_flag', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.Order')),
            ],
        ),
    ]
